main: ch.swisssmp.streets.Streets
version: 1.1
name: Streets
author: detig_iii
description: Erhöht Reisegeschwindigkeit in spezifischen Zonen
depend: [WebCore,WGRegionEvents,WorldGuard]
permissions:
  streets.admin:
    description: Erlaubt die Verwaltung des Plugins
    default: op
commands:
  streets:
    description: Verwaltet das Plugin
    usage: |
      /streets reload - Lädt Strassen neu