main: ch.swisssmp.mobcamps.MobCamps
version: 1.1
api-version: 1.13
name: MobCamps
author: detig_iii
description: Ermöglicht MobCamps mit Ingame Editor, welche in Welten mit der Gamerule doMobCampSawning auf true selbständig Mobs spawnen
depend: [WebCore,RandomItemAPI]
permissions:
  mobcamps.admin:
    description: Erlaubt bearbeiten von MobCamps
    default: op
commands:
  camp:
    description: Zur Verwaltung von Camps - [Parameter] sind Pflicht, (Parameter=Standardwert) sind optional
    usage: |
      /camp erstelle [Name] §7- Erstellt ein neues Camp
      /camp aktualisiere (Name) §7- Aktualisiert Instanzen und Item Stacks dieses Camps
      /camp lade (Welt) §7- Lädt alle Camp Instanzen dieser oder aller Welten
      /camp radius (Name) [Radius] §7- Ändert den Spawn Radius für dieses Camp
      /camp limit (Name) [Limit] §7- Ändert das Spawnlimit für dieses Camp
      /camp trigger (Name) [Distanz] §7- Ändert den Auslöser-Radius für dieses Camp (min 16 Blöcke)
    permission: mobcamps.admin
  camps:
    description: Zeigt alle MobCamps an
    usage: /camps
    permission: mobcamps.admin