main: ch.swisssmp.prismsearch.PrismSearch
version: 1.1
name: PrismSearch
author: detig_iii
description: Werkzeug zur Ingame Suche in der Prism DB
permissions:
  prismsearch.admin:
    description: Erlaubt die Verwendung des Plugins
    default: op
commands:
  search:
    description: Hauptbefehl
    usage: /search - Schaltet die Suche an und ab, Resultate sind im Web-Tool
    permission: prismsearch.admin