main: ch.swisssmp.craftelytra.CraftElytra
version: 2.5
name: CraftElytra
author: detig_iii
description: Crafte Elytra wie andere Items
permissions:
  craftelytra.admin:
    description: Bestimme das Template für Elytra Gates
    default: op
  craftelytra.elytragate.use:
    description: Erhalte einen Boost beim Durchfliegen von Elytra Gates
    default: true
  craftelytra.elytragate.build:
    description: Ermöglicht Errichten von Elytra Gates
    default: op
  craftelytra.craft:
    description: Ermöglicht Crafting von Elytra
    default: op
commands:
  elytragate:
    usage: /elytragate
    permission: craftelytra.admin
depend: [WorldGuard,WGRegionEvents,WebCore]
load: startup