main: ch.swisssmp.adventuredungeons.Main
version: 1.1
name: AdventureDungeons
author: detig_iii
description: Play Dungeons in minecraft without Mods!
depend: [WorldGuard,WebCore]
load: startup
permissions: 
  craftmmo.admin:
    default: op
    description: Allows you to manage Adventure Dungeons
commands:
  CraftMMO:
    description: use general commands of the CraftMMO plugin
    aliases: [mmo]
    permission: craftmmo.admin
  MmoShop:
    description: manage MmoShops
    usage: /MmoShop [action] [arguments]
    aliases: [mmoshop]
    permission: craftmmo.admin
  MmoWorld:
    description: manage MmoWorlds
    usage: /MmoWorld [action] [arguments]
    aliases: [mmoworld]
    permission: craftmmo.admin
  MmoCamp:
    description: manage MmoCamps
    usage: /MmoCamp [action] [arguments]
    aliases: [mmocamp]
    permission: craftmmo.admin
  rename:
    description: rename your currently held item
    usage: /rename [name]
    permission: craftmmo.admin
  MmoRegion:
    description: manage MmoRegions
    usage: /MmoRegion [action] [arguments]
    aliases: [mmoregion]
    permission: craftmmo.admin
  MmoDungeon:
    description: manage MmoDungeons
    usage: /MmoDungeon [action] [arguments]
    aliases: [mmodungeon]
    permission: craftmmo.admin
  MmoMultiState:
    description: manage MmoMultiStates
    usage: /MmoMultiState [action] [arguments]
    aliases: [mmomultistate, multistate]
    permission: craftmmo.admin
  join:
    description: Betrete eine Dungeon Instanz eines anderen Spielers
    usage: /join [Spieler]
  refuse:
    description: Lehne eine Anfrage eines Spielers ab
    usage: /refuse [Spieler]
  choose:
    description: Entscheide bei einer Anfrage
    usage: /choose [ID der Anfrage] [Auswahl]
  invite:
    description: Lade einen Spieler in deine Dungeon Instanz ein
    usage: /invite [Spielername]
    aliases: [inv]
  ready:
    description: Setze deinen Bereitschaftsstatus in einer Dungeon Instanz
    usage: /ready