main: ch.swisssmp.adventuredungeons.AdventureDungeons
version: 3.1.1
name: AdventureDungeons
author: detig_iii
description: Dungeons in Minecraft ohne Mods
depend: [WorldGuard,WebCore]
load: startup
permissions: 
  dungeons.admin:
    default: op
    description: Erlaubt die Verwaltung von AdventureDungeons
commands:
  AdventureDungeons:
    description: Generelle Verwaltung von AdventureDungeons
    aliases: [mmo,dungeons]
    permission: dungeons.admin
  camp:
    description: Verwaltet MmoCamps
    usage: |
      /camp reload - Lädt Camps neu
      /camp spawnpoints [Camp-ID] - Initiiert oder beendet Spawnpoint-Editor
      /camp trigger [Camp-ID] (Instanz-ID) - Löst ein Camp aus
      /camp clear [Camp-ID] (Instanz-ID) - Leert ein Camp
    permission: dungeons.admin
  rename:
    description: Gib dem Item in deiner Hand einen neuen Namen
    usage: /rename [name]
    permission: dungeons.admin
  dungeon:
    description: Verwaltet MmoDungeons
    usage: |
      /dungeon reload
      /dungeon join [Dungeon-ID] [Schwierigkeit] (Spieler)
      /dungeon leave
      /dungeon list
      /dungeon edit [Dungeon-ID]
      /dungeon endedit
      /dungeon warp [Dungeon-ID]
      /dungeon players
      /dungeon respawn_index [Welt] [Respawn-Index]
      /dungeon play_sound [Instanz-ID] [Sound-ID]
    aliases: [mmodungeon]
    permission: dungeons.admin
  join:
    description: Betrete eine Dungeon Instanz eines anderen Spielers
    usage: /join [Spieler]
  leave:
    description: Verlasse eine Dungeon Instanz
    usage: /leave
    aliases: [quit,exit,verlassen]
  refuse:
    description: Lehne eine Anfrage eines Spielers ab
    usage: /refuse [Spieler]
  choose:
    description: Entscheide bei einer Anfrage
    usage: /choose [ID der Anfrage] [Auswahl]
  invite:
    description: Lade einen Spieler in deine Dungeon Instanz ein
    usage: /invite [Spielername]
    aliases: [inv]
  ready:
    description: Setze deinen Bereitschaftsstatus in einer Dungeon Instanz
    usage: /ready