main: ch.swisssmp.world.WorldManager
version: 1.2
name: WorldManager
author: detig_iii
description: L채dt und verwaltet Welten
depend: [WebCore]
permissions:
  worldmanager.admin:
    description: Erlaubt die Verwaltung des Plugins
    default: op
commands:
  worldmanager:
    description: Verwaltet das Plugin
    usage: |
      /worldmanager reload - L채dt und deaktiviert Welten gem채ss Web-Interface
      /worldmanager load [Welt] - L채dt eine Welt
      /worldmanager unload [Welt] (Speichern=True) - Deaktiviert eine Welt, Speichern kann True oder False