main: ch.swisssmp.event.RemoteEventListener
version: 1.6
name: RemoteEventListener
author: detig_iii
description: Führt Befehle vom Web-Interface bei ingame Events aus
depend: [WebCore]
softdepend: [AdventureDungeons,AreaTransformations,WGRegionEvents]
permissions:
  remoteeventlistener.admin:
    description: Erlaubt Verwaltung des Plugins
    default: op
commands:
  remoteeventlistener:
    description: Verwaltet das Plugin
    usage: |
      /remoteeventlistener reload
      /remoteeventlistener debug
      /remoteeventlistener list
    permission: remoteeventlistener.admin