main: ch.swisssmp.transformations.AreaTransformations
version: 1.3
api-version: 1.13
name: AreaTransformations
author: detig_iii
description: Transformierbare Zonen (grosse Tore, Zugbrücken etc.)
depend: [WorldEdit,WebCore]
permissions: 
  transformations.admin:
    default: op
    description: Erlaubt die Verwaltung des Plugins
commands:
  transformation:
    description: Verwaltet Transformationen
    usage: |
      [Transformation] ersetzen mit Enum oder ID
      /transformation reload
      /transformation list
      /transformation register [Transformation] [Zustand]
      /transformation unregister [Transformation] [Zustand]
      /transformation trigger [Welt] [Transformation] [Zustand] (Player)
    aliases: [multistate]
    permission: transformations.admin