main: ch.swisssmp.server.ServerManager
version: 1.0
name: ServerManager
author: detig_iii
description: Displays server info on the web interface
permissions:
  smpserver.admin:
    description: Allows you to use the admin commands
    default: op
commands:
  servermanager:
    description: Reloads the plugin
    usage: |
      /servermanager reload
      /servermanager rename [name]
    permission: smpserver.admin
    aliases: [svm]