main: ch.swisssmp.monuments.Monuments
version: 0.1
api-version: 1.13
name: Monuments
author: Plexon21
depend: [WebCore]
permissions:
  monuments.admin:
    description: Erlaubt die Verwaltung der Monumente
    default: op
commands:
  monuments:
    description: Hauptbefehl zur Verwaltung von Monumenten
    permission: monuments.admin
  monuments reloadCache:
    description: Ladet alle Monumente neu