levels:
  level_1:
    name: 'Apprentis'
    unlocked: true
    threshhold: 20
    duration: 30
    firstclient: 10
    baseinterval: 20
  level_2:
    name: 'Commis de cuisine'
    unlocked: true
    threshhold: 250
    duration: 360
    firstclient: 10
    baseinterval: 20
  level_3:
    name: 'Chef de partie'
    unlocked: false
    threshhold: 350
    duration: 420
    firstclient: 10
    baseinterval: 15
  level_4:
    name: 'Sous Chef'
    unlocked: false
    threshhold: 400
    duration: 480
    firstclient: 5
    baseinterval: 15
  level_5:
    name: 'Chef de cuisine'
    unlocked: false
    threshhold: 0
    duration: 540
    firstclient: 5
    baseinterval: 15
dishes:
  HASH_BROWNS:
    name: 'Röschti'
    price: 12
    recipe:
      - '2x gebratene Kartoffeln'
  MEAT_FEAST:
    name: 'Fleischschmaus'
    price: 16
    recipe:
      - '1x Gebratenes Steak'
      - '1x Gebratenes Poulet'
      - '1x Gebratenes Schweinefleisch'
  HONEY_MILK:
    name: 'Honigmilch'
    price: 6
    recipe:
      - '1x Honigflasche'
      - '1x Milcheimer'
  RICE_PUDDING:
    name: 'Milchreis'
    price: 6
    recipe:
      - '1x Weizen'
      - '1x Milcheimer'
  SUSHI:
    name: 'Sushi'
    price: 12
    recipe:
      - '1x Getrocknetes Seegras'
      - '1x Roher Lachs'
      - '1x Weizen'
  RABBIT_STEW:
    name: 'Hasenragout'
    price: 12
    recipe:
      - '1x Hasenfuss'
      - '1x Kochwasser'
      - '1x Karotte'
      - '1x Kartoffel'
  SCHNITZEL_FRIES:
    name: 'SchniPo'
    price: 16
    recipe:
      - '1x Gebratenes Schweinefleisch'
      - '1x Bratkartoffeln'
      - '1x Weizen'
  VEGGIES_DELIGHT:
    name: 'Veggies Delight'
    price: 8
    recipe:
      - '1x Seegras'
      - '1x Weizen'
      - '1x Karotte'
  SPAGHETTI_BOLOGNESE:
    name: 'Spaghetti Bolognese'
    price: 24
    recipe:
      - '1x Pasta'
      - '1x Rote Sauce'
      - '1x Gebratenes Steak'
  CREEPER_SUCRE:
    name: 'Creeper sucré'
    price: 24
    recipe:
      - '1x Gedünsteter Creeperkopf'
      - '1x Zucker'
      - '1x Sahne'
      - '1x Pufferfischextrakt'
  ZURICH_GESCHNETZELTES:
    name: 'Zürigschnätzlets'
    price: 18
    recipe:
      - '1x Gebratenes Steak'
      - '1x Röschti'
      - '1x Milch'
  HOT_CHOCOLATE:
    name: 'Heissi Schoggi'
    price: 12
    recipe:
      - '1x Zucker'
      - '1x Schoggipulver'
      - '1x Milch'
      - 'Auf Craftingform achten!'
  PEKING_DUCK:
    name: 'Peking Ente'
    price: 14
    recipe:
      - '1x Gebratenes Poulet'
      - '1x Kochwasser'
      - '1x Zucker'
  PIZZA_MARGHERITA:
    name: 'Pizza Margherita'
    price: 20
    recipe:
      - '1x Brot'
      - '1x Rote Sauce'
      - '1x Käse'
  MARITIME_PLATTER:
    name: 'Maritimer Meeresplatte'
    price: 20
    recipe:
      - '1x Gebratener Lachs'
      - '1x Pufferfischextrakt'
      - '1x Gebratenes Seegras'
  LORDS_BLESSING:
    name: 'The lords blessing'
    price: 24
    recipe:
      - '1x Gedünsteter Kürbis'
      - '1x Bratkartoffel'
      - '1x Kochwasser'
      - '1x Sahne'
  DAME_BLANCHE:
    name: 'Coupe Dänemark'
    price: 22
    recipe:
      - '1x Heissi Schoggi'
      - '1x Sahne'
      - '1x Wildbeere'
ingredients:
  COCOA_BEANS:
    initialAmount: 3
    buyAmount: 3
    price: 4
  CARROT:
    initialAmount: 3
    buyAmount: 3
    price: 5
  SUGAR:
    initialAmount: 4
    buyAmount: 4
    price: 6
  COCOA_BEANS:
    initialAmount: 3
    buyAmount: 3
    price: 5
  PORKCHOP:
    initialAmount: 3
    buyAmount: 3
    price: 6
  BEEF:
    initialAmount: 3
    buyAmount: 3
    price: 6
  CHICKEN:
    initialAmount: 3
    buyAmount: 3
    price: 6
  ZVIERI_MILK_BUCKET:
    initialAmount: 3
    buyAmount: 3
    price: 6
  ZVIERI_HONEY_BOTTLE:
    initialAmount: 4
    buyAmount: 4
    price: 6
  PUFFERFISH:
    initialAmount: 3
    buyAmount: 3
    price: 5
  POTATO:
    initialAmount: 6
    buyAmount: 6
    price: 8
  RABBIT_FOOT:
    initialAmount: 2
    buyAmount: 2
    price: 4
  CREEPER_HEAD:
    initialAmount: 2
    buyAmount: 2
    price: 6
  WHEAT:
    initialAmount: 6
    buyAmount: 6
    price: 8
  SALMON:
    initialAmount: 3
    buyAmount: 3
    price: 6
  KELP:
    initialAmount: 3
    buyAmount: 3
    price: 6
  PUMPKIN:
    initialAmount: 2
    buyAmount: 2
    price: 6
  SWEET_BERRIES:
    initialAmount: 2
    buyAmount: 2
    price: 4
  BEETROOT:
    initialAmount: 3
    buyAmount: 3
    price: 4
  COAL:
    initialAmount: 10
    buyAmount: 10
    price: 20
  GLASS_BOTTLE:
    initialAmount: 9
    buyAmount: 9
    price: 5
  ZVIERI_WATER_BUCKET:
    initialAmount: 2
    buyAmount: 2
    price: 6