main: ch.swisssmp.knightstournament.KnightsTournament
version: 1.1
name: KnightsTournament
author: detig_iii
description: Ritterspiele
depend: [WebCore,CustomItems]
permissions: 
  knightstournament.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  knightstournament.host:
    default: op
    description: Erlaubt die Leitung von Turnieren
  knightstournament.craft:
    default: op
    description: Erlaubt das Craften von Turnierlanzen
  knightstournament.participate:
    default: op
    description: Erlaubt die Teilnahme an Ritterspielen
commands:
  knightstournament:
    usage: |
      /knightstournament start [Arena]
      /knightstournament end
    description: Steuert ein Turnier
    permission: knightstournament.admin
    aliases: [ritterspiel]