main: ch.swisssmp.infinibucket.InfiniBucket
version: 1.2
api-version: 1.13
name: InfiniBucket
author: detig_iii
description: Unendlicher Wassereimer
permissions:
  infinibucket.craft:
    description: Erlaubt das Crafting des unendlichen Wassereimers
    default: op
  infinibucket.use:
    description: Erlaubt die Verwendung des unendlichen Wassereimers
    default: op