main: ch.swisssmp.taxcollector.TaxCollector
version: 1.0
name: TaxCollector
author: detig_iii
description: Regelt automatisch Opfergaben und andere Abgaben
depend: [WebCore,SwissSMPUtils]
permissions:
  taxcollector.admin:
    description: Erlaubt die Verwendung des Plugins
    default: op
commands:
  tax:
    description: Steuert das Plugin ingame
    usage: |
      /tax reload
      /tax info [player]
    permission: taxcollector.admin
  abgaben:
    description: Zeigt deine verbleibenden Abgaben an
    usage: /abgaben
    aliases: [abgabe,opfergabe,opfergaben,steuer,steuern]