main: ch.swisssmp.taxcollector.TaxCollector
version: 1.0
name: TaxCollector
author: detig_iii
description: Provides core functionality for other plugins
depend: [WebCore,SwissSMPUtils]
permissions:
  taxcollector.admin:
    description: Allows you to use the plugin
    default: op
commands:
  tax:
    description: Use the plugin
    usage: |
      /tax collect
      /tax info
    permission: taxcollector.admin