main: ch.swisssmp.taxcollector.TaxCollector
version: 1.0
name: TaxCollector
author: detig_iii
description: Provides core functionality for other plugins
depend: [WebCore,SwissSMPUtils]
permissions:
  taxcollector.admin:
    description: Allows you to use admin commands
    default: op
commands:
  tax:
    description: Use the plugin
    usage: |
      /tax reload
      /tax info [player]
    permission: taxcollector.admin
  abgaben:
    description: Zeigt deine verbleibenden Abgaben an
    usage: /abgaben
    aliases: [abgabe,opfergabe,opfergaben,steuer,steuern]