main: ch.swisssmp.taxcollector.TaxCollector
version: 2.1
name: TaxCollector
author: detig_iii
description: Regelt automatisch Opfergaben und andere Abgaben
depend: [WebCore,SwissSMPUtils]
permissions:
  taxcollector.admin:
    description: Erlaubt die Verwendung des Plugins
    default: op
commands:
  tax:
    description: Steuert das Plugin ingame
    usage: |
      /tax collect (city_id) - Abgaben einsammeln
      /tax reload - Kisten aktualisieren
      /tax info [player] - Abgaben eines Spielers anzeigen
    permission: taxcollector.admin
  abgaben:
    description: Zeigt deine verbleibenden Abgaben an
    usage: /abgaben
    aliases: [abgabe,opfergabe,opfergaben,steuer,steuern]