main: ch.swisssmp.craftmmo.Main
version: 1.0
name: CraftMMO
author: detig_iii
description: Play RPG in minecraft without Mods!
depend: [WorldGuard]
load: startup
commands:
  CraftMMO:
    description: use general commands of the CraftMMO plugin
    aliases: [mmo]
  MmoShop:
    description: manage MmoShops
    usage: /MmoShop [action] [arguments]
    aliases: [mmoshop]
  MmoItem:
    description: manage MmoItems
    usage: /MmoItem [action] [arguments]
    aliases: [mmoitem]
  MmoMob:
    description: manage MmoMobs
    usage: /MmoMob [action] [arguments]
    aliases: [mmomob]
  MmoWorld:
    description: manage MmoWorlds
    usage: /MmoWorld [action] [arguments]
    aliases: [mmoworld]
  MmoCamp:
    description: manage MmoCamps
    usage: /MmoCamp [action] [arguments]
    aliases: [mmocamp]
  rename:
    description: rename your currently held item
    usage: /rename [name]
  MmoRegion:
    description: manage MmoRegions
    usage: /MmoRegion [action] [arguments]
    aliases: [mmoregion]
  MmoDungeon:
    description: manage MmoDungeons
    usage: /MmoDungeon [action] [arguments]
    aliases: [mmodungeon]
  MmoCountry:
    description: manage MmoCountries
    usage: /MmoCountry [action] [arguments]
    aliases: [mmocountry]
  MmoMultiState:
    description: manage MmoMultiStates
    usage: /MmoMultiState [action] [arguments]
    aliases: [mmomultistate, multistate]
  party:
    description: manage parties
    usage: /party [action] [arguments]
  talk:
    description: interactive conversation helper command
    usage: /talk [token] [lore_progress_id] [action] [value]
  quests:
    description: questbook summoner
    usage: /quests
    aliases: [q, quest]
  ready:
    description: toggle ready state in a dungeon
    usage: /ready
    aliases: [r]