main: ch.swisssmp.shops.ShopManager
version: 2.0
name: Shops
author: detig_iii
description: Konfigurierbare Villager Shops
load: startup
depend: [WebCore,WorldGuard]
permissions: 
  shop.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  shop.craft:
    default: op
    description: Erlaubt das Craften von Shops
  shop.create:
    default: op
    description: Erlaubt das Erstellen und Verwalten von Shops
commands:
  shop:
    usage: |
      /shop create - Erstellt einen Shop an deiner Position
      /shop info [Shop-ID] - Zeigt Informationen zu diesem Shop
    description: Diverse Admin-Befehle
    permission: shop.admin