name: LaPoste
version: '0.1'
main: ch.swisssmp.LaPostePlugin
api-version: '1.13'
depend: [SwissSMPUtils,CustomItems,Webcore]
author: WhiteGuggi
description: Post-Plugin für SwissSMP Städtesystem
permissions:
  laposte.use:
    default: op
    description: Allows crafting and using Mailboxes for oneself
  laposte.admin:
    default: op
    description: Everything
