main: ch.swisssmp.chatmanager.ChatManager
version: 1.3
api-version: 1.13
name: ChatManager
author: detig_iii
description: Chat-Protokoll, Audiosignale bei Schlüsselwörtern und Chat-Modul im Web-Interface
permissions:
  chatnotifier.personalalert:
    description: Sendet Audiosignale bei Schlüsselwörtern
    default: op
commands:
  chat:
    description: Sendet eine Chat Nachricht
    default: op
    usage: /chat [Absender] [Nachricht]