webserver: http://127.0.0.1/api
token: yourtoken
#set this to true to get output of web traffic in the console
debug: false
buildphase: 15 # value in minutes
countdown: 5 # value in seconds
crystal: DIAMOND_BLOCK
#locations
lobby:
  x: 0
  y: 100
  z: 0
  random: 0
spectate:
  x: 0
  y: 100
  z: 0
  random: 0
#score settings
scores:
  player_kill: 200
  crystal_fuse: 100
  crystal_defuse: 100
  crystal_explode: 500