main: ch.swisssmp.ignitabletorches.IgnitableTorches
version: 1.1
api-version: 1.13
name: IgnitableTorches
author: detig_iii
description: Erlaubt anzünden von Redstone Fackeln mit Feuerzeugen in Welten mit der Gamerule ignitableTorches auf true