main: ch.swisssmp.customitems.CustomItems
version: 3.1
api-version: 1.13
name: CustomItems
author: detig_iii
description: Konfigurierbare Items
depend: [WebCore]
permissions: 
  customitems.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
commands:
  customitems:
    usage: |
      /customitems inspect - Zeit Informationen zum Item in deiner Hand an
      /customitems summon [Item-ID] [Menge]
      /customitems summon [Custom-Enum] [Menge]
      /customitems uploaddata - Lädt Informationen zu Materialien in das Webinterface
    aliases: [customitem]
    description: Steuert CustomItems
    permission: customitems.admin