main: ch.swisssmp.customitems.CustomItems
version: 1.8
name: CustomItems
author: detig_iii
description: Konfigurierbare Items
depend: [WebCore]
permissions: 
  customitems.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
commands:
  customitems:
    usage: |
      /customitems inspect - Funktioniert noch nicht
      /customitems summon [Item-ID] [Menge]
      /customitems summon [Custom-Enum] [Menge]
    aliases: [customitem]
    description: Steuert CustomItems
    permission: customitems.admin
  rename:
    usage: /rename [Name]
    aliases: [umbenennen]
    description: Benennt ein Item neu
    permission: customitems.admin