main: ch.swisssmp.permissionmanager.PermissionManager
version: 1.0
name: PermissionManager
author: detig_iii
description: Enable Permission Management from a Web Interface
depend: [PermissionsEx, WebCore, TabList, SwissSMPUtils]
permissions:
  permissionmanager.admin:
    default: op
    description: Allows you to change settings ingame
  permissionmanager.commands.autocomplete:
    default: op
    description: Allows you to autocomplete commands
commands:
  permission:
    usage: /permission [reload/debug]
    description: Change settings ingame
    permission: permissionmanager.admin