main: ch.swisssmp.addonabnahme.AddonAbnahmePlugin
version: 4
api-version: 1.13
name: AddonAbnahme
depend: [WebCore,CitySystem,NPCs]
softdepend: [LivemapMarkerAPI]
permissions:
  addonabnahme.admin:
    description: Erlaubt die Administration von Addon-Abnahmen
    default: op
  addonabnahme.request:
    description: Erlaubt die Anmeldung eines Addons
    default: false
commands: