main: ch.swisssmp.addonabnahme.AddonAbnahme
version: 1.1
name: AddonAbnahme
depend: [WebCore]
permissions:
  addonabnahme.admin:
    description: Allows you to use the plugin
    default: op
  addonabnahme.request:
    description: Allows you to request an approval
    default: false
commands:
  AddonSign:
    description: Update a sign
    usage: |
           Usage:
           /AddonSign update [addon_instance_id]
           /AddonSign clear [x] [y] [z]
    permission: addonabnahme.admin