main: ch.swisssmp.addonabnahme.AddonAbnahme
version: 2.1
api-version: 1.13
name: AddonAbnahme
depend: [WebCore,CitySystem,NPCs]
permissions:
  addonabnahme.admin:
    description: Erlaubt die Administration von Addon-Abnahmen
    default: op
  addonabnahme.request:
    description: Erlaubt die Anmeldung eines Addons
    default: false
commands:
  addon:
    description: Hauptbefehl zur Verwaltung von Addons
    usage: "Verwendung: /<command> <subcommand> [Argumente]"
    permission: addonabnahme.admin
  addon reload:
    description: Aktualisiert Guides
    usage: "Verwendung: /<command> <subcommand>"
    permission: addonabnahme.admin