webserver: http://127.0.0.1/api/
#this is used to validate your requests
token: yourtoken
#this is used to pass the htaccess authorization
user: yourusername
password: yourpassword
#use this name to identify your server in the web interface
name: WebCoreServer
#set this to true to get output of web traffic in the console
debug: false