main: ch.swisssmp.dynamicwarpportals.Main
version: 1.0
name: DynamicWarpPortals
author: detig_iii
description: Create dynamically linked WarpPortals
commands:
  DynamicWarpPortals:
    description: use commands of the DynamicWarpPortals plugin
    usage: /DynamicWarpPortals
    aliases: [dwp]