main: ch.swisssmp.citymapdisplays.CityMapDisplaysPlugin
version: 1.01
api-version: 1.13
name: CityMapDisplays
author: detig_iii
description: Ermöglicht Echtzeit Displays von Städten aufgrund der Livemap
depend: [LivemapRenderAPI,MapImageLoader,CitySystem]
permissions:
  citymapdisplays.admin:
    description: Erlaubt Verwaltung des Plugins
    default: op
  citymapdisplays.viewer:
    description: Erlaubt Verwendung des Plugins
    default: true
commands:
  citymapdisplay:
    description: Basisbefehl zur Verwaltung von Anzeigen
    usage: "Verwendung: /<command>"
    permission: citymapdisplays.admin
    aliases: [citydisplay]
  citymapdisplay create:
    description: Erstellt eine neue Anzeige
    usage: "Verwendung: /<command> <subcommand> [width] [height]"
    permission: citymapdisplays.admin
  citymapdisplay remove:
    description: Entfernt eine bestehende Anzeige
    usage: "Verwendung: /<command> <subcommand> [display-id]"
    permission: citymapdisplays.admin
  citymapdisplay book:
    description: Beschwört ein Auswahlbuch
    usage: "Verwendung: /<command> <subcommand> [display-id]"
    permission: citymapdisplays.admin
  citymapdisplay list:
    description: Listet alle Anzeigen auf
    usage: "Verwendung: /<command> <subcommand>"
    permission: citymapdisplays.admin
  citymapdisplay reload:
    description: Lädt Anzeigen neu
    usage: "Verwendung: /<command> <subcommand>"
    permission: citymapdisplays.admin
  citymapdisplay show:
    description: Zeigt eine Stadt
    usage: "Verwendung: /<command> <subcommand> [display-id] [city-id]"
    permission: citymapdisplays.viewer