main: ch.swisssmp.livemap_render_api.LivemapRenderAPI
version: 1.0
api-version: 1.13
name: LivemapRenderAPI
author: detig_iii
description: Standardisiert Mapping von Livemap-Ausschnitten auf Ingame-Karten
depend: [MapImageLoader]