main: ch.swisssmp.citysystem.CitySystem
version: 1.0
name: CitySystem
author: detig_iii
description: Ingame Städtesystem Interaktion
depend: [WebCore,CustomItems]
permissions: 
  citysystem.admin:
    default: op
    description: Erlaubt die Steuerung des Plugins
  citysystem.mayor:
    default: op
    description: Erlaubt das Craften des Stadtsiegels
  citysystem.priest:
    default: op
    description: Erlaubt das Craften von Akromas Zepter