main: ch.swisssmp.city.CitySystemPlugin
version: 6
api-version: 1.13
name: CitySystem
authors: [detig_iii,WhiteGuggi]
description: Erlaubt Spielern ingame Verwaltung ihrer Städte
depend: [SwissSMPUtils,WebCore,CustomItems,CustomEditorAPI,NPCs,Ceremonies,RawTextBuilderAPI,Zones]
permissions:
  citysystem.found:
    description: Erlaubt Gründung einer neuen Stadt
    default: op
  citysystem.join:
    description: Erlaubt dir, einer Stadt als Bürger beizutreten
    default: op
  citysystem.admin:
    description: Erlaubt Verwaltung des Plugins
    default: op
commands:
  cities:
    description: Zeigt alle Städte an
    usage: "Verwendung: /<command>"
    permission: citysystem.admin
    aliases: [city]
  cities reload:
    description: Lädt alle Städte neu
    usage: "Verwendung: /<command> reload"
    permission: citysystem.admin
  cities delete:
    description: Löscht eine Stadt und alle zugehörigen Addons
    usage: "Verwendung: /<command> delete [Stadt]"
    permission: citysystem.admin
  cities ring:
    description: Erstellt einen Siegelring
    usage: "Verwendung: /<command> ring [Stadt] (Besitzer) [Typ]"
    permission: citysystem.admin
  addon:
    description: Hauptbefehl zur Verwaltung von Addons
    usage: "Verwendung: /<command> <subcommand> [Argumente]"
    permission: citysystem.admin
  addon reload:
    description: Aktualisiert Guides
    usage: "Verwendung: /<command> <subcommand>"
    permission: citysystem.admin
  techtree:
    description: Hauptbefehl zur Verwaltung von Techtrees
    usage: "Verwendung: /<command> <subcommand> [Argumente]"
    permission: citysystem.admin
  techtree reload:
    description: Aktualisiert Techtrees
    usage: "Verwendung: /<command> <subcommand>"
    permission: citysystem.admin