main: ch.swisssmp.warps.WarpsPlugin
version: 1
api-version: 1.13
name: Warps
author: WhiteGuggi
description: Erlaubt erstellen und nutzen von Warppunkten
permissions:
  smp.commands.warpset:
    description: Erlaubt erstellen und entfernen von Wars
    default: op
  smp.commands.warp:
    description: Erlaubt Verwendung von Wars
    default: op
commands:
  warp:
    description: Warpt zu einem existierenden Warp.
    usage: /warp (warp)
    permission: smp.commands.warp
  warp set:
    description: Erstellt einen neuen Warp
    usage: /warp set (warp)
    permission: smp.commands.warpset
    aliases: [warp create,setwarp]
  warp remove:
    description: Entfernt einen bestehenden Warp
    usage: /warp remove (warp)
    permission: smp.commands.warpset
    aliases: [warp rm,rmwarp,delwarp,warp del]