main: ch.swisssmp.craftsaddle.CraftSaddle
version: 1.2
name: CraftSaddle
author: detig_iii
description: Crafte private Sattel zum Schutz deiner Pferde
permissions:
  craftsaddle.craft:
    description: Erlaubt das Crafting von PrivateSaddles
    default: op