main: ch.swisssmp.craftbank.CraftBank
version: 1.2
name: CraftBank
author: detig_iii
description: Use banks to store experience
permissions:
  craftbank.use:
    description: Allows you to use your bank account
    default: false
  craftbank.employee:
    description: Allows you to set up bank counters and ATMs in your city
    default: false