main: ch.swisssmp.craftbank.CraftBank
version: 1.4
api-version: 1.13
name: CraftBank
author: detig_iii
description: Erlaubt speichern von Erfahrungspunkten in einem virtuellen Bankkonto
permissions:
  craftbank.use:
    description: Erlabut Verwendung des Bankkontos
    default: false
  craftbank.employee:
    description: Erlaubt erstellen von Bankschaltern und Automaten in der Stadt
    default: false