main: ch.swisssmp.spawnmanager.SpawnManager
version: 1.0
name: SpawnManager
author: detig_iii
description: Manages the bed spawn location of players
depend: [SwissSMPUtils, WebCore]
permissions:
  spawnmanager.spawn:
    description: Allows you to teleport to the spawn
    default: op
commands:
  spawn:
    description: Teleport to the world spawn
    usage: /spawn
    permission: spawnmanager.spawn